[build]
  command = "npm run build"   # The build command for your project
  publish = "dist"           # The directory where the built files are located

[context.production.environment]
  NODE_ENV = "production"    # Set environment variables for the production context

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200               # Redirect all routes to index.html (for single-page applications)

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"  # Set caching headers

# Add more configuration options as needed
